apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: application
  labels:
    app: application
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: web
        image: nginx
